export { default as SmallLoader } from './SmallLoader'
export { default as CardLoader } from './CardLoader'
export { default as ItemLoader } from './ItemLoader'
export { default as GreetLoader } from './GreetLoader'
export { default as UpdateLoader } from './UpdatePageLoader'